version: "3.2"
services:
    sq-back-end:
        image: "hudsonwilde/sq-back-end"
        ports:
            - 80:3000
        build:
            context: .
            dockerfile: prod.Dockerfile
        container_name: sq-be-prod
        volumes:
            - "/home/app"
        working_dir: /home/app
